"""Add deleted_at to BaseModel for soft delete

Revision ID: 02c0ef62d61b
Revises: 7482467cd007
Create Date: 2026-02-05 14:57:35.823135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c0ef62d61b'
down_revision: Union[str, Sequence[str], None] = '7482467cd007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessment_case_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.alter_column('assessment_case_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | assistant)',
               existing_comment='참여자 유형 (client | specialist)',
               existing_nullable=False)
    op.add_column('assessment_cases', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessment_send_links', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessment_session_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.alter_column('assessment_session_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | assistant)',
               existing_comment='참여자 유형 (client | specialist)',
               existing_nullable=False)
    op.add_column('assessment_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessment_tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessments', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('center_assessments', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('client_link_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('client_relations', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('client_unlink_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_case_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_cases', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_notes', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_session_attendances', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counselings', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('document_accesses', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('institutions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('login_notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('member_invitations', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('member_non_working_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('member_working_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('non_operating_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('operating_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('password_histories', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('persons', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('role_permissions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('schedules', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('share_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('sibling_relations', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sibling_relations', 'deleted_at')
    op.drop_column('share_tokens', 'deleted_at')
    op.drop_column('schedules', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('role_permissions', 'deleted_at')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('persons', 'deleted_at')
    op.drop_column('permissions', 'deleted_at')
    op.drop_column('password_histories', 'deleted_at')
    op.drop_column('operating_times', 'deleted_at')
    op.drop_column('non_operating_times', 'deleted_at')
    op.drop_column('member_working_times', 'deleted_at')
    op.drop_column('member_non_working_times', 'deleted_at')
    op.drop_column('member_invitations', 'deleted_at')
    op.drop_column('login_notifications', 'deleted_at')
    op.drop_column('institutions', 'deleted_at')
    op.drop_column('document_accesses', 'deleted_at')
    op.drop_column('counselings', 'deleted_at')
    op.drop_column('counseling_sessions', 'deleted_at')
    op.drop_column('counseling_session_attendances', 'deleted_at')
    op.drop_column('counseling_notes', 'deleted_at')
    op.drop_column('counseling_cases', 'deleted_at')
    op.drop_column('counseling_case_participants', 'deleted_at')
    op.drop_column('client_unlink_logs', 'deleted_at')
    op.drop_column('client_relations', 'deleted_at')
    op.drop_column('client_link_requests', 'deleted_at')
    op.drop_column('center_assessments', 'deleted_at')
    op.drop_column('assessments', 'deleted_at')
    op.drop_column('assessment_tasks', 'deleted_at')
    op.drop_column('assessment_sessions', 'deleted_at')
    op.alter_column('assessment_session_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | specialist)',
               existing_comment='참여자 유형 (client | assistant)',
               existing_nullable=False)
    op.drop_column('assessment_session_participants', 'deleted_at')
    op.drop_column('assessment_send_links', 'deleted_at')
    op.drop_column('assessment_cases', 'deleted_at')
    op.alter_column('assessment_case_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | specialist)',
               existing_comment='참여자 유형 (client | assistant)',
               existing_nullable=False)
    op.drop_column('assessment_case_participants', 'deleted_at')
    op.drop_column('accounts', 'deleted_at')
    # ### end Alembic commands ###
