"""description

Revision ID: 161b14e99ee7
Revises: 02c0ef62d61b
Create Date: 2026-02-05 15:34:49.656065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '161b14e99ee7'
down_revision: Union[str, Sequence[str], None] = '02c0ef62d61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessment_case_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.alter_column('assessment_case_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | assistant)',
               existing_comment='참여자 유형 (client | specialist)',
               existing_nullable=False)
    op.add_column('assessment_cases', sa.Column('counselor_id', sa.String(length=36), nullable=False, comment='담당 검사자 ID (Member UUID, 소유권 필터링용)'))
    op.add_column('assessment_cases', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.create_index('ix_assessment_cases_center_counselor', 'assessment_cases', ['center_id', 'counselor_id'], unique=False)
    op.create_index(op.f('ix_assessment_cases_counselor_id'), 'assessment_cases', ['counselor_id'], unique=False)
    op.add_column('assessment_send_links', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('assessment_session_participants', sa.Column('attendance_status', sa.String(length=20), nullable=False, comment='참석 상태 (scheduled, attended, absent)'))
    op.add_column('assessment_session_participants', sa.Column('attended_at', sa.DateTime(), nullable=True, comment='실제 참석 일시 (UTC naive)'))
    op.add_column('assessment_session_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.alter_column('assessment_session_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | assistant)',
               existing_comment='참여자 유형 (client | specialist)',
               existing_nullable=False)
    op.alter_column('assessment_session_participants', 'participant_id',
               existing_type=sa.VARCHAR(length=36),
               comment='참여자 ID (clients.id 또는 center_members.id)',
               existing_comment='참여자 ID',
               existing_nullable=False)
    op.create_index('ix_assessment_session_participants_attendance', 'assessment_session_participants', ['attendance_status'], unique=False)
    op.drop_column('assessment_session_participants', 'assigned_at')
    op.drop_column('assessment_session_participants', 'unassigned_at')
    op.add_column('assessment_sessions', sa.Column('schedule_id', sa.String(length=36), nullable=False, comment='일정 ID (대면 검사 필수, FK 제약 없음)'))
    op.add_column('assessment_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.create_index(op.f('ix_assessment_sessions_schedule_id'), 'assessment_sessions', ['schedule_id'], unique=False)
    op.add_column('assessment_tasks', sa.Column('session_id', sa.String(length=36), nullable=True, comment='세션 ID (onsite Task만 연결, FK 제약 없음)'))
    op.add_column('assessment_tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.create_index('ix_assessment_tasks_session', 'assessment_tasks', ['session_id'], unique=False)
    op.create_index(op.f('ix_assessment_tasks_session_id'), 'assessment_tasks', ['session_id'], unique=False)
    op.add_column('assessments', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('center_assessments', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('client_link_requests', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('client_relations', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('client_unlink_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_case_participants', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_cases', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_notes', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_session_attendances', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counseling_sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('counselings', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('document_accesses', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('institutions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('login_notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('member_invitations', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('member_non_working_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('member_working_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('non_operating_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('operating_times', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('password_histories', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('persons', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('role_permissions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('schedules', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('share_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    op.add_column('sibling_relations', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sibling_relations', 'deleted_at')
    op.drop_column('share_tokens', 'deleted_at')
    op.drop_column('schedules', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('role_permissions', 'deleted_at')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('persons', 'deleted_at')
    op.drop_column('permissions', 'deleted_at')
    op.drop_column('password_histories', 'deleted_at')
    op.drop_column('operating_times', 'deleted_at')
    op.drop_column('non_operating_times', 'deleted_at')
    op.drop_column('member_working_times', 'deleted_at')
    op.drop_column('member_non_working_times', 'deleted_at')
    op.drop_column('member_invitations', 'deleted_at')
    op.drop_column('login_notifications', 'deleted_at')
    op.drop_column('institutions', 'deleted_at')
    op.drop_column('document_accesses', 'deleted_at')
    op.drop_column('counselings', 'deleted_at')
    op.drop_column('counseling_sessions', 'deleted_at')
    op.drop_column('counseling_session_attendances', 'deleted_at')
    op.drop_column('counseling_notes', 'deleted_at')
    op.drop_column('counseling_cases', 'deleted_at')
    op.drop_column('counseling_case_participants', 'deleted_at')
    op.drop_column('client_unlink_logs', 'deleted_at')
    op.drop_column('client_relations', 'deleted_at')
    op.drop_column('client_link_requests', 'deleted_at')
    op.drop_column('center_assessments', 'deleted_at')
    op.drop_column('assessments', 'deleted_at')
    op.drop_index(op.f('ix_assessment_tasks_session_id'), table_name='assessment_tasks')
    op.drop_index('ix_assessment_tasks_session', table_name='assessment_tasks')
    op.drop_column('assessment_tasks', 'deleted_at')
    op.drop_column('assessment_tasks', 'session_id')
    op.drop_index(op.f('ix_assessment_sessions_schedule_id'), table_name='assessment_sessions')
    op.drop_column('assessment_sessions', 'deleted_at')
    op.drop_column('assessment_sessions', 'schedule_id')
    op.add_column('assessment_session_participants', sa.Column('unassigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='조기 종료 시점'))
    op.add_column('assessment_session_participants', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='참여 기록 시점'))
    op.drop_index('ix_assessment_session_participants_attendance', table_name='assessment_session_participants')
    op.alter_column('assessment_session_participants', 'participant_id',
               existing_type=sa.VARCHAR(length=36),
               comment='참여자 ID',
               existing_comment='참여자 ID (clients.id 또는 center_members.id)',
               existing_nullable=False)
    op.alter_column('assessment_session_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | specialist)',
               existing_comment='참여자 유형 (client | assistant)',
               existing_nullable=False)
    op.drop_column('assessment_session_participants', 'deleted_at')
    op.drop_column('assessment_session_participants', 'attended_at')
    op.drop_column('assessment_session_participants', 'attendance_status')
    op.drop_column('assessment_send_links', 'deleted_at')
    op.drop_index(op.f('ix_assessment_cases_counselor_id'), table_name='assessment_cases')
    op.drop_index('ix_assessment_cases_center_counselor', table_name='assessment_cases')
    op.drop_column('assessment_cases', 'deleted_at')
    op.drop_column('assessment_cases', 'counselor_id')
    op.alter_column('assessment_case_participants', 'participant_type',
               existing_type=sa.VARCHAR(length=20),
               comment='참여자 유형 (client | specialist)',
               existing_comment='참여자 유형 (client | assistant)',
               existing_nullable=False)
    op.drop_column('assessment_case_participants', 'deleted_at')
    op.drop_column('accounts', 'deleted_at')
    # ### end Alembic commands ###
