"""add attachments to notices

Revision ID: 16eb3c888969
Revises: fd6ae9bcfbb5
Create Date: 2026-03-05 14:43:15.354356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16eb3c888969'
down_revision: Union[str, Sequence[str], None] = 'fd6ae9bcfbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='첨부파일 목록 [{url, path, name, size, content_type}]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'attachments')
    # ### end Alembic commands ###
