"""refactor 스키마 델타: event 아웃박스 + 신규 테이블 + soft-delete partial unique

Revision ID: 1818f2c3637c
Revises: 421223de7b77
Create Date: 2026-07-01 09:56:19.680894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1818f2c3637c'
down_revision: Union[str, Sequence[str], None] = '421223de7b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_intent_templates',
    sa.Column('center_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index(op.f('ix_agent_intent_templates_center_id'), 'agent_intent_templates', ['center_id'], unique=False, if_not_exists=True)
    op.create_index('ix_intent_templates_active', 'agent_intent_templates', ['is_active'], unique=False, if_not_exists=True)
    op.create_index('ix_intent_templates_center', 'agent_intent_templates', ['center_id', 'is_active'], unique=False, if_not_exists=True)
    op.create_index('ix_intent_templates_kind_active', 'agent_intent_templates', ['kind', 'is_active'], unique=False, if_not_exists=True)
    op.create_index('ix_intent_templates_tool_name', 'agent_intent_templates', ['tool_name'], unique=False, if_not_exists=True)
    op.create_table('assessment_packages',
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('center_member_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('package_price', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index('ix_assessment_packages_center_id', 'assessment_packages', ['center_id'], unique=False, if_not_exists=True)
    op.create_table('client_voucher_resources',
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('client_voucher_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_voucher_id', 'resource_id', name='uq_client_voucher_resource'),
        if_not_exists=True,
    )
    op.create_index('ix_client_voucher_resources_center', 'client_voucher_resources', ['center_id'], unique=False, if_not_exists=True)
    op.create_index('ix_client_voucher_resources_type', 'client_voucher_resources', ['client_voucher_id', 'resource_type'], unique=False, if_not_exists=True)
    op.create_index('ix_client_voucher_resources_voucher', 'client_voucher_resources', ['client_voucher_id'], unique=False, if_not_exists=True)
    op.create_table('counseling_case_analyses',
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('counseling_case_id', sa.String(length=36), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('triggered_by', sa.String(length=36), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index('idx_case_analysis_case', 'counseling_case_analyses', ['counseling_case_id'], unique=False, if_not_exists=True)
    op.create_index('idx_case_analysis_center', 'counseling_case_analyses', ['center_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_counseling_case_analyses_center_id'), 'counseling_case_analyses', ['center_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_counseling_case_analyses_counseling_case_id'), 'counseling_case_analyses', ['counseling_case_id'], unique=False, if_not_exists=True)
    op.create_table('event_atomics',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('act', sa.String(length=20), nullable=False),
    sa.Column('entity_name', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index(op.f('ix_event_atomics_entity_id'), 'event_atomics', ['entity_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_event_atomics_event_id'), 'event_atomics', ['event_id'], unique=False, if_not_exists=True)
    op.create_table('event_reactions',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('reaction', sa.String(length=100), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'reaction', name='uq_event_reaction'),
        if_not_exists=True,
    )
    op.create_index(op.f('ix_event_reactions_event_id'), 'event_reactions', ['event_id'], unique=False, if_not_exists=True)
    op.create_table('events',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('center_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index(op.f('ix_events_center_id'), 'events', ['center_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_events_next_attempt_at'), 'events', ['next_attempt_at'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False, if_not_exists=True)
    op.create_table('form_sends',
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('form_template_id', sa.String(length=36), nullable=False),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index(op.f('ix_form_sends_center_id'), 'form_sends', ['center_id'], unique=False, if_not_exists=True)
    op.create_index('ix_form_sends_center_template', 'form_sends', ['center_id', 'form_template_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_form_sends_form_template_id'), 'form_sends', ['form_template_id'], unique=False, if_not_exists=True)
    op.create_table('notification_logs',
    sa.Column('notification_id', sa.String(length=36), nullable=True),
    sa.Column('center_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )
    op.create_index('ix_notification_logs_notification', 'notification_logs', ['notification_id'], unique=False, if_not_exists=True)
    op.create_index('ix_notification_logs_recipient', 'notification_logs', ['center_id', 'recipient_id', 'created_at'], unique=False, if_not_exists=True)
    op.create_index('ix_notification_logs_status', 'notification_logs', ['status', 'created_at'], unique=False, if_not_exists=True)
    op.drop_constraint(op.f('accounts_email_key'), 'accounts', type_='unique', if_exists=True)
    op.create_index('uq_accounts_email_active', 'accounts', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_constraint(op.f('admin_accounts_email_key'), 'admin_accounts', type_='unique', if_exists=True)
    op.create_index('uq_admin_accounts_email_active', 'admin_accounts', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.alter_column('assessment_sessions', 'schedule_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               comment=None,
               existing_comment='일정 ID (대면 검사 필수, FK 제약 없음)')
    op.drop_constraint(op.f('uq_case_assessment_task'), 'assessment_tasks', type_='unique', if_exists=True)
    op.create_index('uq_case_assessment_task', 'assessment_tasks', ['case_id', 'assessment_id'], unique=True, postgresql_where='deleted_at IS NULL', if_not_exists=True)
    op.drop_constraint(op.f('assessments_code_key'), 'assessments', type_='unique', if_exists=True)
    op.create_index('uq_assessments_code_active', 'assessments', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_constraint(op.f('uq_center_note_pref_center'), 'center_note_preferences', type_='unique', if_exists=True)
    op.drop_index(op.f('ix_center_note_preferences_center_id'), table_name='center_note_preferences', if_exists=True)
    op.create_index(op.f('ix_center_note_preferences_center_id'), 'center_note_preferences', ['center_id'], unique=False, if_not_exists=True)
    op.create_index('uq_center_note_pref_center_active', 'center_note_preferences', ['center_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_constraint(op.f('uq_center_vouchers_center_catalog'), 'center_vouchers', type_='unique', if_exists=True)
    op.create_index('uq_center_vouchers_center_catalog', 'center_vouchers', ['center_id', 'catalog_id'], unique=True, postgresql_where='deleted_at IS NULL', if_not_exists=True)
    op.drop_constraint(op.f('centers_code_key'), 'centers', type_='unique', if_exists=True)
    op.create_index('uq_centers_code_active', 'centers', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_constraint(op.f('uq_clients_center_code'), 'clients', type_='unique', if_exists=True)
    op.create_index('uq_clients_center_code', 'clients', ['center_id', 'code'], unique=True, postgresql_where='deleted_at IS NULL', if_not_exists=True)
    op.alter_column('counseling_case_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='생성 시각 (UTC)',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_counseling_note_session_client'), 'counseling_notes', type_='unique', if_exists=True)
    op.create_index('uq_counseling_note_session_client', 'counseling_notes', ['counseling_session_id', 'client_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.alter_column('counseling_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='생성 시각 (UTC)',
               existing_nullable=False)
    op.alter_column('counseling_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='수정 시각 (UTC)',
               existing_nullable=False)
    op.drop_index(op.f('ix_counseling_sessions_schedule_id'), table_name='counseling_sessions', if_exists=True)
    op.create_index(op.f('ix_counseling_sessions_schedule_id'), 'counseling_sessions', ['schedule_id'], unique=False, if_not_exists=True)
    op.create_index('uq_counseling_session_schedule', 'counseling_sessions', ['schedule_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents', if_exists=True)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions', if_exists=True)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False, if_not_exists=True)
    op.create_index('uq_permissions_code_active', 'permissions', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_constraint(op.f('persons_account_id_key'), 'persons', type_='unique', if_exists=True)
    op.create_index('uq_persons_account_active', 'persons', ['account_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    op.drop_constraint(op.f('uq_role_center_code'), 'roles', type_='unique', if_exists=True)
    op.create_index('uq_role_center_code', 'roles', ['center_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_role_center_code', table_name='roles', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('uq_role_center_code'), 'roles', ['center_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_persons_account_active', table_name='persons', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('persons_account_id_key'), 'persons', ['account_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_permissions_code_active', table_name='permissions', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions', if_exists=True)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False, if_not_exists=True)
    op.drop_index('uq_counseling_session_schedule', table_name='counseling_sessions', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.drop_index(op.f('ix_counseling_sessions_schedule_id'), table_name='counseling_sessions', if_exists=True)
    op.create_index(op.f('ix_counseling_sessions_schedule_id'), 'counseling_sessions', ['schedule_id'], unique=True, if_not_exists=True)
    op.alter_column('counseling_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='수정 시각 (UTC)',
               existing_nullable=False)
    op.alter_column('counseling_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='생성 시각 (UTC)',
               existing_nullable=False)
    op.drop_index('uq_counseling_note_session_client', table_name='counseling_notes', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('uq_counseling_note_session_client'), 'counseling_notes', ['counseling_session_id', 'client_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('counseling_case_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='생성 시각 (UTC)',
               existing_nullable=False)
    op.drop_index('uq_clients_center_code', table_name='clients', postgresql_where='deleted_at IS NULL', if_exists=True)
    op.create_unique_constraint(op.f('uq_clients_center_code'), 'clients', ['center_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_centers_code_active', table_name='centers', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('centers_code_key'), 'centers', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_center_vouchers_center_catalog', table_name='center_vouchers', postgresql_where='deleted_at IS NULL', if_exists=True)
    op.create_unique_constraint(op.f('uq_center_vouchers_center_catalog'), 'center_vouchers', ['center_id', 'catalog_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_center_note_pref_center_active', table_name='center_note_preferences', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.drop_index(op.f('ix_center_note_preferences_center_id'), table_name='center_note_preferences', if_exists=True)
    op.create_index(op.f('ix_center_note_preferences_center_id'), 'center_note_preferences', ['center_id'], unique=True, if_not_exists=True)
    op.create_unique_constraint(op.f('uq_center_note_pref_center'), 'center_note_preferences', ['center_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_assessments_code_active', table_name='assessments', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('assessments_code_key'), 'assessments', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_case_assessment_task', table_name='assessment_tasks', postgresql_where='deleted_at IS NULL', if_exists=True)
    op.create_unique_constraint(op.f('uq_case_assessment_task'), 'assessment_tasks', ['case_id', 'assessment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('assessment_sessions', 'schedule_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               comment='일정 ID (대면 검사 필수, FK 제약 없음)')
    op.drop_index('uq_admin_accounts_email_active', table_name='admin_accounts', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('admin_accounts_email_key'), 'admin_accounts', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_accounts_email_active', table_name='accounts', postgresql_where=sa.text('deleted_at IS NULL'), if_exists=True)
    op.create_unique_constraint(op.f('accounts_email_key'), 'accounts', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_notification_logs_status', table_name='notification_logs', if_exists=True)
    op.drop_index('ix_notification_logs_recipient', table_name='notification_logs', if_exists=True)
    op.drop_index('ix_notification_logs_notification', table_name='notification_logs', if_exists=True)
    op.drop_table('notification_logs', if_exists=True)
    op.drop_index(op.f('ix_form_sends_form_template_id'), table_name='form_sends', if_exists=True)
    op.drop_index('ix_form_sends_center_template', table_name='form_sends', if_exists=True)
    op.drop_index(op.f('ix_form_sends_center_id'), table_name='form_sends', if_exists=True)
    op.drop_table('form_sends', if_exists=True)
    op.drop_index(op.f('ix_events_status'), table_name='events', if_exists=True)
    op.drop_index(op.f('ix_events_next_attempt_at'), table_name='events', if_exists=True)
    op.drop_index(op.f('ix_events_center_id'), table_name='events', if_exists=True)
    op.drop_table('events', if_exists=True)
    op.drop_index(op.f('ix_event_reactions_event_id'), table_name='event_reactions', if_exists=True)
    op.drop_table('event_reactions', if_exists=True)
    op.drop_index(op.f('ix_event_atomics_event_id'), table_name='event_atomics', if_exists=True)
    op.drop_index(op.f('ix_event_atomics_entity_id'), table_name='event_atomics', if_exists=True)
    op.drop_table('event_atomics', if_exists=True)
    op.drop_index(op.f('ix_counseling_case_analyses_counseling_case_id'), table_name='counseling_case_analyses', if_exists=True)
    op.drop_index(op.f('ix_counseling_case_analyses_center_id'), table_name='counseling_case_analyses', if_exists=True)
    op.drop_index('idx_case_analysis_center', table_name='counseling_case_analyses', if_exists=True)
    op.drop_index('idx_case_analysis_case', table_name='counseling_case_analyses', if_exists=True)
    op.drop_table('counseling_case_analyses', if_exists=True)
    op.drop_index('ix_client_voucher_resources_voucher', table_name='client_voucher_resources', if_exists=True)
    op.drop_index('ix_client_voucher_resources_type', table_name='client_voucher_resources', if_exists=True)
    op.drop_index('ix_client_voucher_resources_center', table_name='client_voucher_resources', if_exists=True)
    op.drop_table('client_voucher_resources', if_exists=True)
    op.drop_index('ix_assessment_packages_center_id', table_name='assessment_packages', if_exists=True)
    op.drop_table('assessment_packages', if_exists=True)
    op.drop_index('ix_intent_templates_tool_name', table_name='agent_intent_templates', if_exists=True)
    op.drop_index('ix_intent_templates_kind_active', table_name='agent_intent_templates', if_exists=True)
    op.drop_index('ix_intent_templates_center', table_name='agent_intent_templates', if_exists=True)
    op.drop_index('ix_intent_templates_active', table_name='agent_intent_templates', if_exists=True)
    op.drop_index(op.f('ix_agent_intent_templates_center_id'), table_name='agent_intent_templates', if_exists=True)
    op.drop_table('agent_intent_templates', if_exists=True)
    # ### end Alembic commands ###
