"""add form module

Revision ID: 30e922483335
Revises: 80f9674f0add
Create Date: 2026-02-13 14:53:00.872541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e922483335'
down_revision: Union[str, Sequence[str], None] = '80f9674f0add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('supports_online', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='온라인 검사 지원 여부 (센터 방문 + 태블릿 자가응답)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'supports_online')
    # ### end Alembic commands ###
