"""add case_code to counseling_cases

Revision ID: 4a7068a5140c
Revises: a7f3e2b1c4d5
Create Date: 2026-02-11 10:56:26.633994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a7068a5140c'
down_revision: Union[str, Sequence[str], None] = 'a7f3e2b1c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_attendance_participant'), table_name='counseling_session_attendances')
    op.drop_index(op.f('idx_attendance_session'), table_name='counseling_session_attendances')
    op.drop_index(op.f('ix_counseling_session_attendances_center_id'), table_name='counseling_session_attendances')
    op.drop_index(op.f('ix_counseling_session_attendances_counseling_session_id'), table_name='counseling_session_attendances')
    op.drop_index(op.f('ix_counseling_session_attendances_participant_id'), table_name='counseling_session_attendances')
    op.drop_table('counseling_session_attendances')
    op.add_column('counseling_cases', sa.Column('case_code', sa.String(length=6), nullable=False, comment='케이스 번호 (예: C00001)'))
    op.add_column('counseling_cases', sa.Column('participant_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='참여자 스냅샷 (JSONB)'))
    op.alter_column('counseling_cases', 'total_sessions',
               existing_type=sa.INTEGER(),
               comment='총 회기 수 (계획) - 실무에서는 유동적',
               existing_comment='총 회기 수 (계획)',
               existing_nullable=True)
    op.alter_column('counseling_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='생성 시각 (UTC)',
               existing_nullable=False)
    op.alter_column('counseling_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='수정 시각 (UTC)',
               existing_nullable=False)
    op.drop_index(op.f('ix_counseling_cases_counseling_id'), table_name='counseling_cases')
    op.create_index(op.f('ix_counseling_cases_case_code'), 'counseling_cases', ['case_code'], unique=True)
    op.create_index(op.f('ix_counseling_cases_program_id'), 'counseling_cases', ['program_id'], unique=False)
    op.drop_column('counseling_cases', 'title')
    op.drop_column('counseling_cases', 'goal')
    op.add_column('counseling_notes', sa.Column('client_id', sa.String(length=36), nullable=False, comment='내담자 ID (Client UUID)'))
    op.drop_index(op.f('ix_counseling_notes_counseling_session_id'), table_name='counseling_notes')
    op.create_index(op.f('ix_counseling_notes_counseling_session_id'), 'counseling_notes', ['counseling_session_id'], unique=False)
    op.create_index('idx_note_client', 'counseling_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_counseling_notes_client_id'), 'counseling_notes', ['client_id'], unique=False)
    op.create_unique_constraint('uq_counseling_note_session_client', 'counseling_notes', ['counseling_session_id', 'client_id'])
    op.add_column('counseling_session_participants', sa.Column('is_consumed', sa.Boolean(), nullable=False, comment='회기 소진 여부 (True면 해당 참여자의 total_sessions에서 차감됨)'))
    op.create_index(op.f('ix_counseling_session_participants_is_consumed'), 'counseling_session_participants', ['is_consumed'], unique=False)
    op.add_column('counseling_sessions', sa.Column('session_number', sa.Integer(), nullable=True, comment='회기 번호 (1, 2, 3, ...)'))
    op.alter_column('members', 'permissions_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment=None,
               existing_comment='권한 버전 (권한/역할 변경 감지용)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'permissions_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='권한 버전 (권한/역할 변경 감지용)',
               existing_nullable=False)
    op.drop_column('counseling_sessions', 'session_number')
    op.drop_index(op.f('ix_counseling_session_participants_is_consumed'), table_name='counseling_session_participants')
    op.drop_column('counseling_session_participants', 'is_consumed')
    op.drop_constraint('uq_counseling_note_session_client', 'counseling_notes', type_='unique')
    op.drop_index(op.f('ix_counseling_notes_client_id'), table_name='counseling_notes')
    op.drop_index('idx_note_client', table_name='counseling_notes')
    op.drop_index(op.f('ix_counseling_notes_counseling_session_id'), table_name='counseling_notes')
    op.create_index(op.f('ix_counseling_notes_counseling_session_id'), 'counseling_notes', ['counseling_session_id'], unique=True)
    op.drop_column('counseling_notes', 'client_id')
    op.add_column('counseling_cases', sa.Column('goal', sa.VARCHAR(length=1000), autoincrement=False, nullable=True, comment='상담 목표'))
    op.add_column('counseling_cases', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='케이스 제목'))
    op.drop_index(op.f('ix_counseling_cases_program_id'), table_name='counseling_cases')
    op.drop_index(op.f('ix_counseling_cases_case_code'), table_name='counseling_cases')
    op.create_index(op.f('ix_counseling_cases_counseling_id'), 'counseling_cases', ['program_id'], unique=False)
    op.alter_column('counseling_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='수정 시각 (UTC)',
               existing_nullable=False)
    op.alter_column('counseling_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='생성 시각 (UTC)',
               existing_nullable=False)
    op.alter_column('counseling_cases', 'total_sessions',
               existing_type=sa.INTEGER(),
               comment='총 회기 수 (계획)',
               existing_comment='총 회기 수 (계획) - 실무에서는 유동적',
               existing_nullable=True)
    op.drop_column('counseling_cases', 'participant_snapshot')
    op.drop_column('counseling_cases', 'case_code')
    op.create_table('counseling_session_attendances',
    sa.Column('center_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='센터 ID (UUID)'),
    sa.Column('counseling_session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='상담 회기 ID (UUID)'),
    sa.Column('participant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='참여자 ID (CounselingCaseParticipant.id)'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='출석 상태 (attended, absent, late, excused)'),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='출석 메모'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='UUID Primary Key'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('counseling_session_attendances_pkey'))
    )
    op.create_index(op.f('ix_counseling_session_attendances_participant_id'), 'counseling_session_attendances', ['participant_id'], unique=False)
    op.create_index(op.f('ix_counseling_session_attendances_counseling_session_id'), 'counseling_session_attendances', ['counseling_session_id'], unique=False)
    op.create_index(op.f('ix_counseling_session_attendances_center_id'), 'counseling_session_attendances', ['center_id'], unique=False)
    op.create_index(op.f('idx_attendance_session'), 'counseling_session_attendances', ['counseling_session_id'], unique=False)
    op.create_index(op.f('idx_attendance_participant'), 'counseling_session_attendances', ['participant_id'], unique=False)
    # ### end Alembic commands ###
