"""add admin_accounts and admin_refresh_tokens tables

Revision ID: 7936744b9eff
Revises: 16eb3c888969
Create Date: 2026-03-05 15:49:34.807429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7936744b9eff'
down_revision: Union[str, Sequence[str], None] = '16eb3c888969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_accounts',
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일 (로그인 ID)'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='비밀번호 해시 (bcrypt)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='이름'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='역할 (super_admin, admin, customer_service)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('token_version', sa.Integer(), nullable=False, comment='JWT 버전 (권한 변경 시 증가, 즉시 로그아웃)'),
    sa.Column('failed_login_count', sa.Integer(), nullable=False, comment='연속 로그인 실패 횟수 (성공 시 리셋)'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='계정 잠금 해제 시각 (null이면 잠금 아님)'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='마지막 로그인 시각 (UTC)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_refresh_tokens',
    sa.Column('admin_account_id', sa.String(length=36), nullable=False, comment='연결된 AdminAccount UUID'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='토큰 해시 (SHA-256)'),
    sa.Column('device_info', sa.String(length=500), nullable=True, comment='User-Agent'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 주소 (IPv6 지원)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='만료 시각 (UTC)'),
    sa.Column('used_at', sa.DateTime(), nullable=True, comment='토큰 사용 시각 (일회용 검증)'),
    sa.Column('parent_token_id', sa.String(length=36), nullable=True, comment='이전 토큰 ID (토큰 패밀리 추적)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_refresh_tokens')
    op.drop_table('admin_accounts')
    # ### end Alembic commands ###
