"""Add counseling module tables

Revision ID: a0571f99b8e6
Revises: 1a0bd55e0260
Create Date: 2026-02-03 10:15:57.515324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0571f99b8e6'
down_revision: Union[str, Sequence[str], None] = '1a0bd55e0260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='JWT 버전 (권한 변경 시 증가, 즉시 로그아웃)',
               existing_nullable=False)
    op.alter_column('client_link_requests', 'center_id',
               existing_type=sa.VARCHAR(length=36),
               comment='센터 ID (UUID)',
               existing_comment='센터 ID',
               existing_nullable=False)
    op.alter_column('clients', 'center_id',
               existing_type=sa.VARCHAR(length=36),
               comment='센터 ID (UUID)',
               existing_comment='센터 ID',
               existing_nullable=False)
    op.create_index(op.f('ix_schedules_member_id'), 'schedules', ['member_id'], unique=False)
    op.alter_column('share_tokens', 'document_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('share_tokens', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('share_tokens', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               comment='UUID Primary Key',
               existing_nullable=False)
    op.alter_column('sibling_relations', 'center_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_comment='센터 ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sibling_relations', 'center_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_comment='센터 ID',
               existing_nullable=False)
    op.alter_column('share_tokens', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='UUID Primary Key',
               existing_nullable=False)
    op.alter_column('share_tokens', 'created_by',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('share_tokens', 'document_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_schedules_member_id'), table_name='schedules')
    op.alter_column('clients', 'center_id',
               existing_type=sa.VARCHAR(length=36),
               comment='센터 ID',
               existing_comment='센터 ID (UUID)',
               existing_nullable=False)
    op.alter_column('client_link_requests', 'center_id',
               existing_type=sa.VARCHAR(length=36),
               comment='센터 ID',
               existing_comment='센터 ID (UUID)',
               existing_nullable=False)
    op.alter_column('accounts', 'token_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='JWT 버전 (권한 변경 시 증가, 즉시 로그아웃)',
               existing_nullable=False)
    # ### end Alembic commands ###
