"""add original_name to documents

Revision ID: a95740587a55
Revises: 39d32c7ec4ff
Create Date: 2026-02-24 14:28:58.767076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95740587a55'
down_revision: Union[str, Sequence[str], None] = '39d32c7ec4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_name', sa.String(length=255), nullable=True))
    # 기존 데이터 backfill: original_name = name (원본 파일명)
    op.execute("UPDATE documents SET original_name = name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_name')
    # ### end Alembic commands ###
