"""add_inquiries_and_faqs_tables

Revision ID: d78425ebd687
Revises: c0ed455c18e5
Create Date: 2026-03-10 09:13:30.569931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd78425ebd687'
down_revision: Union[str, Sequence[str], None] = 'c0ed455c18e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # inquiries 테이블 생성 (없을 때만)
    if not conn.dialect.has_table(conn, "inquiries"):
        op.create_table('inquiries',
            sa.Column('center_id', sa.String(36), nullable=True, comment='관련 센터 ID'),
            sa.Column('center_name', sa.String(200), nullable=True, comment='센터명 비정규화'),
            sa.Column('inquiry_type', sa.String(30), nullable=False, comment='유형: general/technical/feature_request/other'),
            sa.Column('status', sa.String(20), nullable=False, comment='상태: pending/in_progress/resolved/closed'),
            sa.Column('subject', sa.String(300), nullable=False, comment='문의 제목'),
            sa.Column('content', sa.Text(), nullable=False, comment='문의 내용'),
            sa.Column('sender_name', sa.String(100), nullable=False, comment='문의자 이름'),
            sa.Column('sender_email', sa.String(200), nullable=False, comment='문의자 이메일'),
            sa.Column('answered_by', sa.String(36), nullable=True, comment='답변 관리자 account_id'),
            sa.Column('answered_by_name', sa.String(100), nullable=True, comment='답변 관리자 이름 비정규화'),
            sa.Column('answer', sa.Text(), nullable=True, comment='답변 내용'),
            sa.Column('answered_at', sa.String(), nullable=True, comment='답변 일시'),
            sa.Column('id', sa.String(36), nullable=False, comment='UUID Primary Key'),
            sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
            sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
            sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
            sa.PrimaryKeyConstraint('id', name=op.f('inquiries_pkey'))
        )
        op.create_index(op.f('idx_inquiries_status'), 'inquiries', ['status', 'created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
        op.create_index(op.f('idx_inquiries_center'), 'inquiries', ['center_id', 'created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')

    # faqs 테이블 생성 (없을 때만)
    if not conn.dialect.has_table(conn, "faqs"):
        op.create_table('faqs',
            sa.Column('category', sa.String(50), nullable=False, comment='카테고리: getting_started/general/technical/feature'),
            sa.Column('question', sa.String(500), nullable=False, comment='질문'),
            sa.Column('answer', sa.Text(), nullable=False, comment='답변'),
            sa.Column('is_published', sa.Boolean(), nullable=False, comment='게시 여부'),
            sa.Column('sort_order', sa.Integer(), nullable=False, comment='카테고리 내 정렬 순서'),
            sa.Column('created_by', sa.String(36), nullable=False, comment='작성자 admin account_id'),
            sa.Column('id', sa.String(36), nullable=False, comment='UUID Primary Key'),
            sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
            sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
            sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
            sa.PrimaryKeyConstraint('id', name=op.f('faqs_pkey'))
        )
        op.create_index(op.f('idx_faqs_category_order'), 'faqs', ['category', 'sort_order'], unique=False, postgresql_where='((is_published = true) AND (deleted_at IS NULL))')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('center_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='관련 센터 ID'),
    sa.Column('center_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='센터명 비정규화'),
    sa.Column('inquiry_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='유형: general/technical/feature_request/other'),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='상태: pending/in_progress/resolved/closed'),
    sa.Column('subject', sa.VARCHAR(length=300), autoincrement=False, nullable=False, comment='문의 제목'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='문의 내용'),
    sa.Column('sender_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='문의자 이름'),
    sa.Column('sender_email', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='문의자 이메일'),
    sa.Column('answered_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True, comment='답변 관리자 account_id'),
    sa.Column('answered_by_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='답변 관리자 이름 비정규화'),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True, comment='답변 내용'),
    sa.Column('answered_at', sa.VARCHAR(), autoincrement=False, nullable=True, comment='답변 일시'),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('inquiries_pkey'))
    )
    op.create_index(op.f('idx_inquiries_status'), 'inquiries', ['status', 'created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_inquiries_center'), 'inquiries', ['center_id', 'created_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_table('faqs',
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='카테고리: getting_started/general/technical/feature'),
    sa.Column('question', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='질문'),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False, comment='답변'),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='게시 여부'),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False, comment='카테고리 내 정렬 순서'),
    sa.Column('created_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='작성자 admin account_id'),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id', name=op.f('faqs_pkey'))
    )
    op.create_index(op.f('idx_faqs_category_order'), 'faqs', ['category', 'sort_order'], unique=False, postgresql_where='((is_published = true) AND (deleted_at IS NULL))')
    # ### end Alembic commands ###
