"""add session_rule jsonb to counseling_cases

Revision ID: efc3541b94a1
Revises: dc33403b8798
Create Date: 2026-03-16 14:42:29.110874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc3541b94a1'
down_revision: Union[str, Sequence[str], None] = 'dc33403b8798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_accounts', 'role',
               existing_type=sa.VARCHAR(length=30),
               comment='역할 (system_admin, super_admin, admin, customer_service)',
               existing_comment='역할 (super_admin, admin, customer_service)',
               existing_nullable=False)

    # 이미 배포된 DB에 컬럼이 존재할 수 있으므로 확인 후 추가
    bind = op.get_bind()
    result = bind.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = 'counseling_cases' AND column_name = 'session_rule'"
    ))
    if not result.fetchone():
        op.add_column('counseling_cases', sa.Column('session_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='회기 생성 규칙 (recurrence, duration_minutes, room_id, start_time)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counseling_cases', 'session_rule')
    op.alter_column('admin_accounts', 'role',
               existing_type=sa.VARCHAR(length=30),
               comment='역할 (super_admin, admin, customer_service)',
               existing_comment='역할 (system_admin, super_admin, admin, customer_service)',
               existing_nullable=False)
    # ### end Alembic commands ###
