"""add notices table

Revision ID: fd6ae9bcfbb5
Revises: c3a7f1b2d4e6
Create Date: 2026-03-05 11:22:43.808859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6ae9bcfbb5'
down_revision: Union[str, Sequence[str], None] = 'c3a7f1b2d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('title', sa.String(length=200), nullable=False, comment='공지 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='공지 내용'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='유형: maintenance, update, announcement'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='게시 여부'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='상단 고정 여부'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='최초 게시 시각 (UTC)'),
    sa.Column('created_by', sa.String(length=36), nullable=False, comment='작성자 account_id'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notices_published', 'notices', ['is_published', 'is_pinned', 'created_at'], unique=False, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notices_published', table_name='notices', postgresql_where='deleted_at IS NULL')
    op.drop_table('notices')
    # ### end Alembic commands ###
