"""audit_log_trace_id_nullable_actor_indexes

Revision ID: 4acc6ede2e06
Revises: e82773eb83d5
Create Date: 2026-04-27 15:58:45.036140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acc6ede2e06'
down_revision: Union[str, None] = 'e82773eb83d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('trace_id', sa.String(length=36), nullable=True))
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('audit_logs', 'actor_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('audit_logs', 'institution_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_inst_created', 'audit_logs', ['institution_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_trace_id'), 'audit_logs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_trace_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_inst_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.alter_column('audit_logs', 'institution_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('audit_logs', 'actor_role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'actor_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('audit_logs', 'trace_id')
    op.alter_column('accounts', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
