"""add rorschach tables

Revision ID: 61a24c5d67bb
Revises: 59b250045d03
Create Date: 2026-04-27 14:15:58.235412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a24c5d67bb'
down_revision: Union[str, None] = '59b250045d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rorschach_regions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('card_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('path_json', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('audio_timestamp_start_sec', sa.Float(), nullable=True),
    sa.Column('audio_timestamp_end_sec', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rorschach_regions_card_no'), 'rorschach_regions', ['card_no'], unique=False)
    op.create_index(op.f('ix_rorschach_regions_session_id'), 'rorschach_regions', ['session_id'], unique=False)
    op.create_table('rorschach_responses',
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('response_no', sa.Integer(), nullable=True),
    sa.Column('free_association_text', sa.Text(), nullable=True),
    sa.Column('inquiry_text', sa.Text(), nullable=True),
    sa.Column('ai_coding_json', sa.JSON(), nullable=True),
    sa.Column('final_coding_json', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rorschach_responses_region_id'), 'rorschach_responses', ['region_id'], unique=True)
    op.create_table('rorschach_sessions',
    sa.Column('examination_id', sa.String(length=36), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('audio_duration_sec', sa.Float(), nullable=True),
    sa.Column('transcript_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID Primary Key'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 시각 (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 시각 (UTC)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 시각 (UTC, Soft Delete)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rorschach_sessions_examination_id'), 'rorschach_sessions', ['examination_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rorschach_sessions_examination_id'), table_name='rorschach_sessions')
    op.drop_table('rorschach_sessions')
    op.drop_index(op.f('ix_rorschach_responses_region_id'), table_name='rorschach_responses')
    op.drop_table('rorschach_responses')
    op.drop_index(op.f('ix_rorschach_regions_session_id'), table_name='rorschach_regions')
    op.drop_index(op.f('ix_rorschach_regions_card_no'), table_name='rorschach_regions')
    op.drop_table('rorschach_regions')
    # ### end Alembic commands ###
