"""auth_lockout_fields

Revision ID: e82773eb83d5
Revises: c36e61597208
Create Date: 2026-04-27 15:43:58.556346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82773eb83d5'
down_revision: Union[str, None] = 'c36e61597208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 기존 행에 적용될 server_default 명시 (NOT NULL + 기본값 0)
    op.add_column('accounts', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('accounts', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('last_login_ip', sa.String(length=45), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_login_ip')
    op.drop_column('accounts', 'last_login_at')
    op.drop_column('accounts', 'lockout_until')
    op.drop_column('accounts', 'failed_login_attempts')
    # ### end Alembic commands ###
