from __future__ import annotations

from typing import Protocol


class StorageClient(Protocol):
    async def upload_file(self, file_data: bytes, path: str, content_type: str) -> dict: ...
    async def download_file(self, path: str, version_id: str | None = None) -> bytes: ...
    async def delete_file(self, path: str) -> None: ...
    async def list_versions(self, path: str) -> list[dict]: ...
    async def restore_version(self, path: str, version_id: str) -> dict: ...
    async def get_presigned_url(
        self, path: str, version_id: str | None = None, expires_in: int = 3600,
    ) -> str: ...
    async def head_file(self, path: str) -> dict | None: ...
    async def get_presigned_upload_url(
        self, path: str, content_type: str, expires_in: int = 900,
    ) -> str: ...
    def get_public_url(self, path: str) -> str: ...
