# ruff: noqa: F401

from app.modules.activity.router import router as activity_router
from app.modules.ai_lab.feature_test.router import router as ai_lab_feature_test_router
from app.modules.assessment.send_link.router import public_router as assessment_send_link_public_router
from app.modules.assessment.send_result.router import public_router as assessment_send_result_public_router
from app.modules.assistant.conversation.router import router as assistant_conversation_router
from app.modules.care_board.router import router as care_board_router
from app.modules.auth.router import router as auth_router
from app.modules.billing.price_list.router import router as billing_price_list_router
from app.modules.billing.billable.router import router as billing_billable_router
from app.modules.billing.payment.router import router as billing_payment_router
from app.modules.client_app.router import app_router as client_app_router
from app.modules.client_app.router import staff_router as client_app_staff_router
from app.modules.counseling.counseling_case.router import router as counseling_case_router
from app.modules.counseling.counseling_note.router import router as counseling_note_router
from app.modules.counseling.counseling_session.router import router as counseling_session_router
from app.modules.counseling.counseling_case_analysis.router import router as counseling_case_analysis_router
from app.modules.counseling.counseling_note_ai_draft.router import router as counseling_note_ai_draft_router
from app.modules.counseling.counseling_note_share.router import router as counseling_note_share_router
from app.modules.field_note.field_note.router import router as field_note_router
from app.modules.field_note.pipeline.router import router as field_note_pipeline_router
from app.modules.field_note.streaming.ws_handler import router as field_note_streaming_router
from app.modules.form.template.router import router as form_template_router
from app.modules.form.form.router import router as form_instance_router
from app.modules.form.send.router import router as form_send_router
from app.modules.form.send.router import public_router as form_link_public_router
from app.modules.institution.router import router as institution_router
from app.modules.llm.router import router as llm_router
from app.modules.messaging.message_template.admin_router import admin_router as messaging_admin_router
from app.modules.messaging.message_template.router import router as messaging_router
from app.modules.notice.router import router as notice_router
from app.modules.notification.notification_setting.router import router as notification_setting_router
from app.modules.person.credential.router import router as person_credential_router
from app.modules.person.person.router import router as person_router
from app.modules.platform_admin.router import router as platform_admin_router
from app.modules.role.role_permission.router import router as role_permission_router
from app.modules.schedule.schedule_change_request.router import change_request_router as schedule_change_request_router
from app.modules.schedule.schedule.home_router import home_router as schedule_home_router
from app.modules.schedule.schedule.router import router as schedule_router
from app.modules.subscription.subscription.admin_router import admin_router as subscription_admin_router
from app.modules.subscription.subscription.router import center_router as subscription_center_router
from app.modules.subscription.subscription.internal_router import internal_router as subscription_internal_router
from app.modules.subscription.subscription.webhook_router import webhook_router as subscription_webhook_router
from app.modules.support.router import router as support_router
from app.modules.voucher.center_voucher.router import router as voucher_center_router
from app.modules.voucher.client_voucher.router import router as voucher_client_router
from app.modules.upload.image.router import router as upload_image_router
from app.modules.role.permission.router import router as role_permission_catalog_router
from app.modules.role.role.router import router as role_role_router
from app.modules.document.document.router import router as document_document_router
from app.modules.document.document_access.router import router as document_document_access_router
from app.modules.document.share_token.router import router as document_share_token_router
from app.modules.client.favorite.router import router as client_favorite_router
from app.modules.client.profile.router import router as client_profile_router
from app.modules.client.relation.router import router as client_relation_router
from app.modules.client.link.router import router as client_link_router
from app.modules.client.resource.router import router as client_resource_router
from app.modules.notification.notification.router import router as notification_notification_router
from app.modules.notification.push_token.router import router as notification_push_token_router
from app.modules.ai_lab.prompt_version.router import router as ai_lab_prompt_version_router
from app.modules.ai_lab.experiment_run.router import router as ai_lab_experiment_run_router
from app.modules.ai_lab.production_config.router import router as ai_lab_production_config_router
from app.modules.ai_lab.sample_dataset.router import router as ai_lab_sample_dataset_router
from app.modules.ai_lab.experiment_group.router import router as ai_lab_experiment_group_router
from app.modules.ai_lab.metadata.router import router as ai_lab_metadata_router
from app.modules.ai_lab.playground.router import router as ai_lab_playground_router
from app.modules.assessment.assessment.router import router as assessment_assessment_router
from app.modules.assessment.center_assessment.router import router as assessment_center_assessment_router
from app.modules.assessment.assessment_set.router import router as assessment_assessment_set_router
from app.modules.assessment.assessment_package.router import router as assessment_assessment_package_router
from app.modules.assessment.assessment_case.router import router as assessment_assessment_case_router
from app.modules.assessment.assessment_case_participant.router import router as assessment_assessment_case_participant_router
from app.modules.assessment.assessment_task.router import router as assessment_assessment_task_router
from app.modules.assessment.assessment_session.router import router as assessment_assessment_session_router
from app.modules.assessment.send_link.router import router as assessment_send_link_router
from app.modules.assessment.send_result.router import router as assessment_send_result_router
from app.modules.center.center.router import router as center_center_router
from app.modules.center.center_application.router import router as center_center_application_router
from app.modules.center.room.router import router as center_room_router
from app.modules.center.center_operating_time.router import router as center_center_operating_time_router
from app.modules.center.center_non_operating_time.router import router as center_center_non_operating_time_router
from app.modules.center.member.router import router as center_member_router
from app.modules.center.member_working_time.router import router as center_member_working_time_router
from app.modules.center.member_non_working_time.router import router as center_member_non_working_time_router
from app.modules.center.me.router import router as center_me_router
from app.modules.center.program.router import router as center_program_router
from app.modules.center.program_member.router import router as center_program_member_router
from app.modules.center.center_note_preference.router import router as center_center_note_preference_router
