apiVersion: v1
kind: Service
metadata:
  name: mindscope-redis-svc
  namespace: mindscope-prod
  labels:
    app: mindscope-redis
spec:
  selector:
    app: mindscope-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
