apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindscope-web
  namespace: mindscope-dev
  labels:
    app: mindscope-web
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindscope-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mindscope-web
        environment: dev
    spec:
      containers:
        - name: web
          image: 786180311928.dkr.ecr.ap-northeast-2.amazonaws.com/mindscope-prod/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mindscope-web-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
